server:
  port: 8089

logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: ERROR
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./h2/oocl-agile-fs
    driverClassName: org.h2.Driver
    username: sa
    password:
